import React from 'react';
import { withRouter } from 'react-router-dom';
// withRouter is a higher order function, it allows access to the router
// when you wrap the export with withRouter it gives access to the location, history & match props
// the location, history, match props are generated by the router on any component that is routed.

import './menu-item.styles.scss';

const MenuItem = ({ title, imageUrl, size, history, linkUrl, match }) => (
  <div className={`${size} menu-item`} onClick={() => history.push(`${match.url}${linkUrl}`)}>
    <div className="background-image" style={{ backgroundImage: `url(${imageUrl})` }}></div>
    <div className="content">
      <h1 className="title">{title}</h1>
      <span className="subtitle">SHOP NOW</span>
    </div>
  </div>
);

export default withRouter(MenuItem);
